wechat_api_test_1:
    path:     /cardsign
    defaults: { _controller: WechatApiBundle:Test:cardsign }

wechat_api_test2:
    path:     /cardpage
    defaults: { _controller: WechatApiBundle:Test:cardpage }
